 archive/migrateToSQLite.js        |  16 [32m+[m[31m--[m
 commands/add.js                   |   8 [32m+[m[31m-[m
 commands/clear.js                 |  10 [32m+[m[31m-[m
 commands/complete.js              |   2 [32m+[m[31m-[m
 commands/delete.js                |   2 [32m+[m[31m-[m
 commands/export.js                |  10 [32m+[m[31m-[m
 commands/import.js                |  20 [32m+[m[31m--[m
 commands/list.js                  |   2 [32m+[m[31m-[m
 commands/search.js                |   4 [32m+[m[31m-[m
 commands/stats.js                 |   2 [32m+[m[31m-[m
 commands/uncomplete.js            |   2 [32m+[m[31m-[m
 commands/update.js                |   4 [32m+[m[31m-[m
 database/database.js              |  10 [32m+[m[31m-[m
 database/noteRepository.js        |  10 [32m+[m[31m-[m
 eslint.config.js                  |  20 [32m+[m[31m--[m
 filters/noteFilter.js             |   2 [32m+[m[31m-[m
 helpers/confirm.js                |   6 [32m+[m[31m-[m
 index.js                          | 112 [32m++++++++[m[31m--------[m
 jest.config.js                    |  18 [32m+[m[31m--[m
 services/exportService.js         |  60 [32m++++[m[31m-----[m
 services/importService.js         |  20 [32m+[m[31m--[m
 services/noteService.js           | 110 [32m++++++++[m[31m--------[m
 sorters/noteSorter.js             |  14 [32m+[m[31m-[m
 tests/exportNotes.test.js         |  48 [32m+++[m[31m----[m
 tests/exportService.test.js       |  76 [32m+++++[m[31m------[m
 tests/importParsers.test.js       |  50 [32m+++[m[31m----[m
 tests/importService.test.js       | 166 [32m++++++++++++[m[31m------------[m
 tests/noteRepository.test.js      |  32 [32m++[m[31m---[m
 tests/noteService.test.js         | 266 [32m+++++++++++++++++++[m[31m-------------------[m
 tests/setup.js                    |   4 [32m+[m[31m-[m
 ui/colors.js                      |   4 [32m+[m[31m-[m
 ui/table.js                       |  14 [32m+[m[31m-[m
 utils/importParsers.js            |  26 [32m++[m[31m--[m
 validators/dueDateValidator.js    |   4 [32m+[m[31m-[m
 validators/priorityValidator.js   |   4 [32m+[m[31m-[m
 validators/recurrenceValidator.js |   4 [32m+[m[31m-[m
 validators/tagValidator.js        |   4 [32m+[m[31m-[m
 validators/textValidator.js       |   2 [32m+[m[31m-[m
 38 files changed, 584 insertions(+), 584 deletions(-)
